// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *FFConsumerKey(void);
FOUNDATION_EXPORT NSString *FFConsumerSecret(void);
