// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

#import "EnvSecrets.h"

static NSString *FFDecode(const uint8_t *cipherEven, size_t cipherEvenLen,
                          const uint8_t *cipherOdd, size_t cipherOddLen,
                          const uint8_t *maskEven, size_t maskEvenLen,
                          const uint8_t *maskOdd, size_t maskOddLen,
                          size_t length) {
  NSMutableData *data = [NSMutableData dataWithLength:length];
  uint8_t *out = (uint8_t *)data.mutableBytes;
  for (size_t i = 0; i < length; i += 1) {
    BOOL even = (i % 2) == 0;
    size_t index = i / 2;
    uint8_t cipher = even ? (index < cipherEvenLen ? cipherEven[index] : 0)
                         : (index < cipherOddLen ? cipherOdd[index] : 0);
    uint8_t mask = even ? (index < maskEvenLen ? maskEven[index] : 0)
                       : (index < maskOddLen ? maskOdd[index] : 0);
    out[i] = (uint8_t)(cipher ^ mask);
  }
  NSString *result = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
  return result ?: @"";
}

static const uint8_t kConsumerKeyCipherEven[] = {181, 71, 184, 126, 131, 2, 29, 75, 18, 21, 145, 245, 54, 111, 222, 4};
static const uint8_t kConsumerKeyCipherOdd[] = {140, 176, 45, 112, 242, 25, 128, 54, 51, 87, 212, 44, 199, 84, 147, 95};
static const uint8_t kConsumerKeyMaskEven[] = {141, 113, 219, 29, 230, 55, 127, 126, 34, 113, 243, 148, 2, 89, 239, 50};
static const uint8_t kConsumerKeyMaskOdd[] = {238, 136, 29, 69, 144, 42, 185, 3, 7, 49, 224, 20, 246, 108, 162, 62};

static const uint8_t kConsumerSecretCipherEven[] = {34, 216, 245, 80, 152, 166, 7, 247, 9, 64, 52, 127, 149, 102, 213, 219};
static const uint8_t kConsumerSecretCipherOdd[] = {111, 192, 212, 219, 98, 160, 150, 245, 14, 203, 118, 63, 207, 66, 97, 10};
static const uint8_t kConsumerSecretMaskEven[] = {21, 237, 192, 104, 175, 196, 54, 146, 106, 118, 85, 29, 164, 85, 180, 235};
static const uint8_t kConsumerSecretMaskOdd[] = {90, 249, 236, 189, 1, 153, 242, 150, 57, 173, 68, 12, 253, 119, 2, 104};

NSString *FFConsumerKey(void) {
  return FFDecode(kConsumerKeyCipherEven, 16, kConsumerKeyCipherOdd, 16, kConsumerKeyMaskEven, 16, kConsumerKeyMaskOdd, 16, 32);
}

NSString *FFConsumerSecret(void) {
  return FFDecode(kConsumerSecretCipherEven, 16, kConsumerSecretCipherOdd, 16, kConsumerSecretMaskEven, 16, kConsumerSecretMaskOdd, 16, 32);
}
