// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

#import "EnvSecrets.h"

static NSString *FFDecode(const uint8_t *cipherEven, size_t cipherEvenLen,
                          const uint8_t *cipherOdd, size_t cipherOddLen,
                          const uint8_t *maskEven, size_t maskEvenLen,
                          const uint8_t *maskOdd, size_t maskOddLen,
                          size_t length) {
  NSMutableData *data = [NSMutableData dataWithLength:length];
  uint8_t *out = (uint8_t *)data.mutableBytes;
  for (size_t i = 0; i < length; i += 1) {
    BOOL even = (i % 2) == 0;
    size_t index = i / 2;
    uint8_t cipher = even ? (index < cipherEvenLen ? cipherEven[index] : 0)
                         : (index < cipherOddLen ? cipherOdd[index] : 0);
    uint8_t mask = even ? (index < maskEvenLen ? maskEven[index] : 0)
                       : (index < maskOddLen ? maskOdd[index] : 0);
    out[i] = (uint8_t)(cipher ^ mask);
  }
  NSString *result = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
  return result ?: @"";
}

static const uint8_t kConsumerKeyCipherEven[] = {72, 252, 207, 94, 64, 29, 254, 172, 74, 48, 24, 48, 121, 238, 252, 211};
static const uint8_t kConsumerKeyCipherOdd[] = {66, 137, 143, 244, 61, 4, 179, 180, 36, 17, 126, 246, 24, 146, 214, 77};
static const uint8_t kConsumerKeyMaskEven[] = {112, 202, 172, 61, 37, 40, 156, 153, 122, 84, 122, 81, 77, 216, 205, 229};
static const uint8_t kConsumerKeyMaskOdd[] = {32, 177, 191, 193, 95, 55, 138, 129, 16, 119, 74, 206, 41, 170, 231, 44};

static const uint8_t kConsumerSecretCipherEven[] = {101, 34, 203, 106, 207, 91, 160, 45, 114, 87, 23, 51, 28, 179, 247, 234};
static const uint8_t kConsumerSecretCipherOdd[] = {150, 72, 39, 141, 43, 189, 77, 254, 243, 232, 158, 28, 0, 97, 229, 78};
static const uint8_t kConsumerSecretMaskEven[] = {82, 23, 254, 82, 248, 57, 145, 72, 17, 97, 118, 81, 45, 128, 150, 218};
static const uint8_t kConsumerSecretMaskOdd[] = {163, 113, 31, 235, 72, 132, 41, 157, 196, 142, 172, 47, 50, 84, 134, 44};

NSString *FFConsumerKey(void) {
  return FFDecode(kConsumerKeyCipherEven, 16, kConsumerKeyCipherOdd, 16, kConsumerKeyMaskEven, 16, kConsumerKeyMaskOdd, 16, 32);
}

NSString *FFConsumerSecret(void) {
  return FFDecode(kConsumerSecretCipherEven, 16, kConsumerSecretCipherOdd, 16, kConsumerSecretMaskEven, 16, kConsumerSecretMaskOdd, 16, 32);
}
