// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

#import "EnvSecrets.h"

static NSString *FFDecode(const uint8_t *cipherEven, size_t cipherEvenLen,
                          const uint8_t *cipherOdd, size_t cipherOddLen,
                          const uint8_t *maskEven, size_t maskEvenLen,
                          const uint8_t *maskOdd, size_t maskOddLen,
                          size_t length) {
  NSMutableData *data = [NSMutableData dataWithLength:length];
  uint8_t *out = (uint8_t *)data.mutableBytes;
  for (size_t i = 0; i < length; i += 1) {
    BOOL even = (i % 2) == 0;
    size_t index = i / 2;
    uint8_t cipher = even ? (index < cipherEvenLen ? cipherEven[index] : 0)
                         : (index < cipherOddLen ? cipherOdd[index] : 0);
    uint8_t mask = even ? (index < maskEvenLen ? maskEven[index] : 0)
                       : (index < maskOddLen ? maskOdd[index] : 0);
    out[i] = (uint8_t)(cipher ^ mask);
  }
  NSString *result = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
  return result ?: @"";
}

static const uint8_t kConsumerKeyCipherEven[] = {249, 154, 209, 71, 165, 245, 4, 139, 70, 180, 206, 234, 241, 24, 198, 73};
static const uint8_t kConsumerKeyCipherOdd[] = {87, 165, 159, 9, 235, 246, 27, 4, 161, 91, 184, 166, 155, 211, 163, 40};
static const uint8_t kConsumerKeyMaskEven[] = {193, 172, 178, 36, 192, 192, 102, 190, 118, 208, 172, 139, 197, 46, 247, 127};
static const uint8_t kConsumerKeyMaskOdd[] = {53, 157, 175, 60, 137, 197, 34, 49, 149, 61, 140, 158, 170, 235, 146, 73};

static const uint8_t kConsumerSecretCipherEven[] = {183, 255, 123, 77, 145, 48, 29, 238, 220, 220, 203, 57, 231, 46, 67, 211};
static const uint8_t kConsumerSecretCipherOdd[] = {230, 85, 250, 177, 77, 73, 200, 30, 190, 26, 208, 65, 110, 65, 111, 255};
static const uint8_t kConsumerSecretMaskEven[] = {128, 202, 78, 117, 166, 82, 44, 139, 191, 234, 170, 91, 214, 29, 34, 227};
static const uint8_t kConsumerSecretMaskOdd[] = {211, 108, 194, 215, 46, 112, 172, 125, 137, 124, 226, 114, 92, 116, 12, 157};

NSString *FFConsumerKey(void) {
  return FFDecode(kConsumerKeyCipherEven, 16, kConsumerKeyCipherOdd, 16, kConsumerKeyMaskEven, 16, kConsumerKeyMaskOdd, 16, 32);
}

NSString *FFConsumerSecret(void) {
  return FFDecode(kConsumerSecretCipherEven, 16, kConsumerSecretCipherOdd, 16, kConsumerSecretMaskEven, 16, kConsumerSecretMaskOdd, 16, 32);
}
