// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

package im.cxa.fanatter

internal object EnvSecrets {
  private data class Obfuscated(
    val length: Int,
    val cipherEven: IntArray,
    val cipherOdd: IntArray,
    val maskEven: IntArray,
    val maskOdd: IntArray,
  )

  private fun decode(data: Obfuscated): String {
    val chars = CharArray(data.length)
    for (i in 0 until data.length) {
      val even = i % 2 == 0
      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]
      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]
      chars[i] = (cipher xor mask).toChar()
    }
    return String(chars)
  }

  private val consumerKeyData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(103, 254, 124, 136, 97, 204, 200, 171, 44, 16, 151, 53, 151, 65, 16, 58),
    cipherOdd = intArrayOf(109, 132, 93, 16, 133, 59, 67, 173, 183, 156, 96, 101, 84, 160, 181, 168),
    maskEven = intArrayOf(95, 200, 31, 235, 4, 249, 170, 158, 28, 116, 245, 84, 163, 119, 33, 12),
    maskOdd = intArrayOf(15, 188, 109, 37, 231, 8, 122, 152, 131, 250, 84, 93, 101, 152, 132, 201),
  )

  private val consumerSecretData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(19, 56, 160, 143, 161, 89, 151, 185, 122, 87, 35, 242, 223, 116, 96, 120),
    cipherOdd = intArrayOf(101, 231, 77, 28, 185, 180, 85, 149, 143, 55, 62, 47, 59, 222, 6, 57),
    maskEven = intArrayOf(36, 13, 149, 183, 150, 59, 166, 220, 25, 97, 66, 144, 238, 71, 1, 72),
    maskOdd = intArrayOf(80, 222, 117, 122, 218, 141, 49, 246, 184, 81, 12, 28, 9, 235, 101, 91),
  )

  fun consumerKey(): String = decode(consumerKeyData)
  fun consumerSecret(): String = decode(consumerSecretData)
}
