// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

package im.cxa.fanatter

internal object EnvSecrets {
  private data class Obfuscated(
    val length: Int,
    val cipherEven: IntArray,
    val cipherOdd: IntArray,
    val maskEven: IntArray,
    val maskOdd: IntArray,
  )

  private fun decode(data: Obfuscated): String {
    val chars = CharArray(data.length)
    for (i in 0 until data.length) {
      val even = i % 2 == 0
      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]
      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]
      chars[i] = (cipher xor mask).toChar()
    }
    return String(chars)
  }

  private val consumerKeyData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(72, 88, 150, 172, 116, 183, 167, 85, 187, 169, 97, 157, 144, 206, 76, 107),
    cipherOdd = intArrayOf(248, 220, 236, 184, 128, 17, 196, 219, 239, 125, 70, 81, 196, 183, 118, 177),
    maskEven = intArrayOf(112, 110, 245, 207, 17, 130, 197, 96, 139, 205, 3, 252, 164, 248, 125, 93),
    maskOdd = intArrayOf(154, 228, 220, 141, 226, 34, 253, 238, 219, 27, 114, 105, 245, 143, 71, 208),
  )

  private val consumerSecretData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(86, 226, 28, 96, 212, 203, 116, 7, 43, 205, 205, 127, 153, 242, 226, 202),
    cipherOdd = intArrayOf(151, 65, 183, 88, 162, 255, 40, 153, 231, 127, 1, 124, 164, 125, 30, 193),
    maskEven = intArrayOf(97, 215, 41, 88, 227, 169, 69, 98, 72, 251, 172, 29, 168, 193, 131, 250),
    maskOdd = intArrayOf(162, 120, 143, 62, 193, 198, 76, 250, 208, 25, 51, 79, 150, 72, 125, 163),
  )

  fun consumerKey(): String = decode(consumerKeyData)
  fun consumerSecret(): String = decode(consumerSecretData)
}
