// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

package im.cxa.fanatter

internal object EnvSecrets {
  private data class Obfuscated(
    val length: Int,
    val cipherEven: IntArray,
    val cipherOdd: IntArray,
    val maskEven: IntArray,
    val maskOdd: IntArray,
  )

  private fun decode(data: Obfuscated): String {
    val chars = CharArray(data.length)
    for (i in 0 until data.length) {
      val even = i % 2 == 0
      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]
      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]
      chars[i] = (cipher xor mask).toChar()
    }
    return String(chars)
  }

  private val consumerKeyData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(56, 129, 37, 27, 117, 129, 45, 204, 231, 46, 216, 227, 1, 115, 0, 86),
    cipherOdd = intArrayOf(252, 146, 15, 60, 218, 160, 100, 75, 29, 176, 224, 66, 36, 5, 239, 20),
    maskEven = intArrayOf(0, 183, 70, 120, 16, 180, 79, 249, 215, 74, 186, 130, 53, 69, 49, 96),
    maskOdd = intArrayOf(158, 170, 63, 9, 184, 147, 93, 126, 41, 214, 212, 122, 21, 61, 222, 117),
  )

  private val consumerSecretData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(33, 72, 60, 230, 178, 72, 65, 19, 137, 120, 155, 141, 147, 28, 176, 84),
    cipherOdd = intArrayOf(115, 81, 178, 64, 152, 21, 58, 44, 168, 148, 141, 77, 16, 31, 75, 123),
    maskEven = intArrayOf(22, 125, 9, 222, 133, 42, 112, 118, 234, 78, 250, 239, 162, 47, 209, 100),
    maskOdd = intArrayOf(70, 104, 138, 38, 251, 44, 94, 79, 159, 242, 191, 126, 34, 42, 40, 25),
  )

  fun consumerKey(): String = decode(consumerKeyData)
  fun consumerSecret(): String = decode(consumerSecretData)
}
