/* eslint-env node */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envFile = process.env.ENVFILE || '.env';
const envPath = path.isAbsolute(envFile)
  ? envFile
  : path.join(rootDir, envFile);
const outputAndroidPath = path.join(
  rootDir,
  'android',
  'app',
  'src',
  'main',
  'java',
  'im',
  'cxa',
  'fanatter',
  'EnvSecrets.kt',
);
const outputIosHeaderPath = path.join(rootDir, 'ios', 'yifan', 'EnvSecrets.h');
const outputIosImplPath = path.join(rootDir, 'ios', 'yifan', 'EnvSecrets.m');

const parseEnv = content => {
  const env = {};
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const match = trimmed.match(/^([A-Za-z0-9_.-]+)\s*=\s*(.*)$/);
    if (!match) {
      continue;
    }
    const key = match[1];
    let value = match[2] ?? '';
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    value = value.replace(/\\n/g, '\n');
    env[key] = value;
  }
  return env;
};

const ensureDir = dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
};

const readEnvFile = () => {
  if (!fs.existsSync(envPath)) {
    console.warn(`[env] Missing ${envFile}. Generated empty config.`);
    return {};
  }
  const contents = fs.readFileSync(envPath, 'utf8');
  return parseEnv(contents);
};

const SENSITIVE_KEYS = new Set([
  'FANFOU_CONSUMER_KEY',
  'FANFOU_CONSUMER_SECRET',
]);

const splitParity = bytes => {
  const even = [];
  const odd = [];
  for (let i = 0; i < bytes.length; i += 1) {
    if (i % 2 === 0) {
      even.push(bytes[i]);
    } else {
      odd.push(bytes[i]);
    }
  }
  return { even, odd };
};

const buildObfuscated = value => {
  const plain = Buffer.from(value ?? '', 'utf8');
  const mask = crypto.randomBytes(plain.length);
  const cipher = Buffer.alloc(plain.length);
  for (let i = 0; i < plain.length; i += 1) {
    // eslint-disable-next-line no-bitwise
    cipher[i] = plain[i] ^ mask[i];
  }
  const cipherParts = splitParity(cipher);
  const maskParts = splitParity(mask);
  return {
    length: plain.length,
    cipherEven: cipherParts.even,
    cipherOdd: cipherParts.odd,
    maskEven: maskParts.even,
    maskOdd: maskParts.odd,
  };
};

const serializeAndroid = env => {
  const sensitive = {};
  for (const key of SENSITIVE_KEYS) {
    sensitive[key] = buildObfuscated(env[key] ?? '');
  }
  const lines = [];
  lines.push('// This file is auto-generated by scripts/generate-env.js');
  lines.push('// Do not edit manually.');
  lines.push('');
  lines.push('package im.cxa.fanatter');
  lines.push('');
  lines.push('internal object EnvSecrets {');
  lines.push('  private data class Obfuscated(');
  lines.push('    val length: Int,');
  lines.push('    val cipherEven: IntArray,');
  lines.push('    val cipherOdd: IntArray,');
  lines.push('    val maskEven: IntArray,');
  lines.push('    val maskOdd: IntArray,');
  lines.push('  )');
  lines.push('');
  lines.push('  private fun decode(data: Obfuscated): String {');
  lines.push('    val chars = CharArray(data.length)');
  lines.push('    for (i in 0 until data.length) {');
  lines.push('      val even = i % 2 == 0');
  lines.push(
    '      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]',
  );
  lines.push(
    '      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]',
  );
  lines.push('      chars[i] = (cipher xor mask).toChar()');
  lines.push('    }');
  lines.push('    return String(chars)');
  lines.push('  }');
  lines.push('');
  const keyData = sensitive.FANFOU_CONSUMER_KEY;
  const secretData = sensitive.FANFOU_CONSUMER_SECRET;
  lines.push('  private val consumerKeyData = Obfuscated(');
  lines.push(`    length = ${keyData.length},`);
  lines.push(`    cipherEven = intArrayOf(${keyData.cipherEven.join(', ')}),`);
  lines.push(`    cipherOdd = intArrayOf(${keyData.cipherOdd.join(', ')}),`);
  lines.push(`    maskEven = intArrayOf(${keyData.maskEven.join(', ')}),`);
  lines.push(`    maskOdd = intArrayOf(${keyData.maskOdd.join(', ')}),`);
  lines.push('  )');
  lines.push('');
  lines.push('  private val consumerSecretData = Obfuscated(');
  lines.push(`    length = ${secretData.length},`);
  lines.push(
    `    cipherEven = intArrayOf(${secretData.cipherEven.join(', ')}),`,
  );
  lines.push(`    cipherOdd = intArrayOf(${secretData.cipherOdd.join(', ')}),`);
  lines.push(`    maskEven = intArrayOf(${secretData.maskEven.join(', ')}),`);
  lines.push(`    maskOdd = intArrayOf(${secretData.maskOdd.join(', ')}),`);
  lines.push('  )');
  lines.push('');
  lines.push('  fun consumerKey(): String = decode(consumerKeyData)');
  lines.push('  fun consumerSecret(): String = decode(consumerSecretData)');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
};

const serializeIosHeader = () =>
  [
    '// This file is auto-generated by scripts/generate-env.js',
    '// Do not edit manually.',
    '',
    '#import <Foundation/Foundation.h>',
    '',
    'FOUNDATION_EXPORT NSString *FFConsumerKey(void);',
    'FOUNDATION_EXPORT NSString *FFConsumerSecret(void);',
    '',
  ].join('\n');

const serializeIosImpl = env => {
  const sensitive = {};
  for (const key of SENSITIVE_KEYS) {
    sensitive[key] = buildObfuscated(env[key] ?? '');
  }
  const keyData = sensitive.FANFOU_CONSUMER_KEY;
  const secretData = sensitive.FANFOU_CONSUMER_SECRET;
  const lines = [];
  lines.push('// This file is auto-generated by scripts/generate-env.js');
  lines.push('// Do not edit manually.');
  lines.push('');
  lines.push('#import "EnvSecrets.h"');
  lines.push('');
  lines.push(
    'static NSString *FFDecode(const uint8_t *cipherEven, size_t cipherEvenLen,',
  );
  lines.push(
    '                          const uint8_t *cipherOdd, size_t cipherOddLen,',
  );
  lines.push(
    '                          const uint8_t *maskEven, size_t maskEvenLen,',
  );
  lines.push(
    '                          const uint8_t *maskOdd, size_t maskOddLen,',
  );
  lines.push('                          size_t length) {');
  lines.push('  NSMutableData *data = [NSMutableData dataWithLength:length];');
  lines.push('  uint8_t *out = (uint8_t *)data.mutableBytes;');
  lines.push('  for (size_t i = 0; i < length; i += 1) {');
  lines.push('    BOOL even = (i % 2) == 0;');
  lines.push('    size_t index = i / 2;');
  lines.push(
    '    uint8_t cipher = even ? (index < cipherEvenLen ? cipherEven[index] : 0)',
  );
  lines.push(
    '                         : (index < cipherOddLen ? cipherOdd[index] : 0);',
  );
  lines.push(
    '    uint8_t mask = even ? (index < maskEvenLen ? maskEven[index] : 0)',
  );
  lines.push(
    '                       : (index < maskOddLen ? maskOdd[index] : 0);',
  );
  lines.push('    out[i] = (uint8_t)(cipher ^ mask);');
  lines.push('  }');
  lines.push(
    '  NSString *result = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];',
  );
  lines.push('  return result ?: @"";');
  lines.push('}');
  lines.push('');
  lines.push(
    `static const uint8_t kConsumerKeyCipherEven[] = {${keyData.cipherEven.join(
      ', ',
    )}};`,
  );
  lines.push(
    `static const uint8_t kConsumerKeyCipherOdd[] = {${keyData.cipherOdd.join(
      ', ',
    )}};`,
  );
  lines.push(
    `static const uint8_t kConsumerKeyMaskEven[] = {${keyData.maskEven.join(
      ', ',
    )}};`,
  );
  lines.push(
    `static const uint8_t kConsumerKeyMaskOdd[] = {${keyData.maskOdd.join(
      ', ',
    )}};`,
  );
  lines.push('');
  lines.push(
    `static const uint8_t kConsumerSecretCipherEven[] = {${secretData.cipherEven.join(
      ', ',
    )}};`,
  );
  lines.push(
    `static const uint8_t kConsumerSecretCipherOdd[] = {${secretData.cipherOdd.join(
      ', ',
    )}};`,
  );
  lines.push(
    `static const uint8_t kConsumerSecretMaskEven[] = {${secretData.maskEven.join(
      ', ',
    )}};`,
  );
  lines.push(
    `static const uint8_t kConsumerSecretMaskOdd[] = {${secretData.maskOdd.join(
      ', ',
    )}};`,
  );
  lines.push('');
  lines.push('NSString *FFConsumerKey(void) {');
  lines.push(
    `  return FFDecode(kConsumerKeyCipherEven, ${keyData.cipherEven.length}, kConsumerKeyCipherOdd, ${keyData.cipherOdd.length}, kConsumerKeyMaskEven, ${keyData.maskEven.length}, kConsumerKeyMaskOdd, ${keyData.maskOdd.length}, ${keyData.length});`,
  );
  lines.push('}');
  lines.push('');
  lines.push('NSString *FFConsumerSecret(void) {');
  lines.push(
    `  return FFDecode(kConsumerSecretCipherEven, ${secretData.cipherEven.length}, kConsumerSecretCipherOdd, ${secretData.cipherOdd.length}, kConsumerSecretMaskEven, ${secretData.maskEven.length}, kConsumerSecretMaskOdd, ${secretData.maskOdd.length}, ${secretData.length});`,
  );
  lines.push('}');
  lines.push('');
  return lines.join('\n');
};

const env = readEnvFile();
ensureDir(path.dirname(outputAndroidPath));
ensureDir(path.dirname(outputIosHeaderPath));
fs.writeFileSync(outputAndroidPath, serializeAndroid(env), 'utf8');
fs.writeFileSync(outputIosHeaderPath, serializeIosHeader(), 'utf8');
fs.writeFileSync(outputIosImplPath, serializeIosImpl(env), 'utf8');
console.log(
  `[env] Generated ${path.relative(
    rootDir,
    outputAndroidPath,
  )}, ${path.relative(rootDir, outputIosHeaderPath)}, ${path.relative(
    rootDir,
    outputIosImplPath,
  )}`,
);
