/* eslint-disable */
// This file is generated by rn-file-routing. Do not edit manually.
import type { RouteNode } from 'rn-file-routing';
import Route___root from './routes/__root';
import Route__auth_home_index from './routes/_auth.home/index';
import Route__auth_index from './routes/_auth.index';
import Route__auth_mentions_index from './routes/_auth.mentions/index';
import Route__auth_more_index from './routes/_auth.more/index';
import Route__auth_profile__handle_index from './routes/_auth.profile.$handle/index';
import Route__auth_status__statusId_index from './routes/_auth.status.$statusId/index';
import Route__auth_tag__tag_index from './routes/_auth.tag.$tag/index';
import Route__auth from './routes/_auth';
import Route_login_index from './routes/login/index';

export const routeTree: RouteNode = 
{
  id: '__root',
  name: '__root',
  pathSegment: '',
  component: Route___root,
  children: [
{
    id: '__root._auth',
    name: 'route_root._auth',
    pathSegment: null,
    component: Route__auth,
    isPathless: true,
    children: [
{
      id: '__root._auth.home',
      name: 'route_root._auth.home',
      pathSegment: 'home',
      children: [
{
        id: '__root._auth.home.index',
        name: 'route_root._auth.home.index',
        pathSegment: '',
        component: Route__auth_home_index,
        isIndex: true,
        children: [],
      }
      ],
    },
{
      id: '__root._auth.index',
      name: 'route_root._auth.index',
      pathSegment: '',
      component: Route__auth_index,
      isIndex: true,
      children: [],
    },
{
      id: '__root._auth.mentions',
      name: 'route_root._auth.mentions',
      pathSegment: 'mentions',
      children: [
{
        id: '__root._auth.mentions.index',
        name: 'route_root._auth.mentions.index',
        pathSegment: '',
        component: Route__auth_mentions_index,
        isIndex: true,
        children: [],
      }
      ],
    },
{
      id: '__root._auth.more',
      name: 'route_root._auth.more',
      pathSegment: 'more',
      children: [
{
        id: '__root._auth.more.index',
        name: 'route_root._auth.more.index',
        pathSegment: '',
        component: Route__auth_more_index,
        isIndex: true,
        children: [],
      }
      ],
    },
{
      id: '__root._auth.profile',
      name: 'route_root._auth.profile',
      pathSegment: 'profile',
      children: [
{
        id: '__root._auth.profile.$handle',
        name: 'route_root._auth.profile._handle',
        pathSegment: ':handle',
        children: [
{
          id: '__root._auth.profile.$handle.index',
          name: 'route_root._auth.profile._handle.index',
          pathSegment: '',
          component: Route__auth_profile__handle_index,
          isIndex: true,
          children: [],
        }
        ],
      }
      ],
    },
{
      id: '__root._auth.status',
      name: 'route_root._auth.status',
      pathSegment: 'status',
      children: [
{
        id: '__root._auth.status.$statusId',
        name: 'route_root._auth.status._statusId',
        pathSegment: ':statusId',
        children: [
{
          id: '__root._auth.status.$statusId.index',
          name: 'route_root._auth.status._statusId.index',
          pathSegment: '',
          component: Route__auth_status__statusId_index,
          isIndex: true,
          children: [],
        }
        ],
      }
      ],
    },
{
      id: '__root._auth.tag',
      name: 'route_root._auth.tag',
      pathSegment: 'tag',
      children: [
{
        id: '__root._auth.tag.$tag',
        name: 'route_root._auth.tag._tag',
        pathSegment: ':tag',
        children: [
{
          id: '__root._auth.tag.$tag.index',
          name: 'route_root._auth.tag._tag.index',
          pathSegment: '',
          component: Route__auth_tag__tag_index,
          isIndex: true,
          children: [],
        }
        ],
      }
      ],
    }
    ],
  },
{
    id: '__root.login',
    name: 'route_root.login',
    pathSegment: 'login',
    children: [
{
      id: '__root.login.index',
      name: 'route_root.login.index',
      pathSegment: '',
      component: Route_login_index,
      isIndex: true,
      children: [],
    }
    ],
  }
  ],
}
;
